export const SET_CAR_TYPE = "SET_CAR_TYPE"
export const SET_CAR_TYPE_PAGE = "SET_CAR_TYPE_PAGE"
export const SET_CAR_TYPE_PAGE_COUNT = "SET_CAR_TYPE_PAGE_COUNT"
export const SET_CAR_TYPE_FILTER = "SET_CAR_TYPE_FILTER"
