export const SET_RATE_TYPE = "SET_RATE_TYPE"
export const SET_RATE_TYPE_PAGE = "SET_RATE_TYPE_PAGE"
export const SET_RATE_TYPE_PAGE_COUNT = "SET_RATE_TYPE_PAGE_COUNT"
export const SET_RATE_TYPE_FILTER = "SET_RATE_TYPE_FILTER"
