export const SET_CITY_LIST = "SET_CITY_LIST"
export const SET_CITY_LIST_PAGE = "SET_CITY_LIST_PAGE"
export const SET_CITY_LIST_PAGE_COUNT = "SET_CITY_LIST_PAGE_COUNT"
export const SET_CITY_LIST_FILTER = "SET_CITY_LIST_FILTER"
